- Default (Linux).sublime-keymap
- Default (OSX).sublime-keymap
- Default (Windows).sublime-keymap
- Default.sublime-commands
- SQLTools.py
- SQLTools.sublime-settings
- SQLToolsModels.py
Also adds functions to autocomplete list.
Partially implements #13 (only for PostgreSQL).
> list functions (ctrl+e ctrl+f) and get their definitions

- README.md
- index.html
> Add new safe_limit, show_query and extend_to_paragraph options

- README.md
- index.md
Simple update to mention new explain query plan functionality.
Related to #64, #75, #77
> Mention new explain query command

- ISSUE_TEMPLATE.md
Adds RDBMS to ISSUE_TEMPLATE.md for tracking problems with RDMBS specific features/queries.
> Add RDBMS to ISSUE_TEMPLATE

- SQLTools.sublime-settings
Add support for MySQL `Describe Function`.
> Add support for MySQL describe function

- SQLToolsAPI/Command.py
Reduces code duplication related to `show_query` functionality.
Fix timing output, which actually displays time in seconds (not milliseconds).
> Review of show_query code, fix time (in seconds)

- SQLToolsAPI/Connection.py
> Fix Query History

- SQLToolsAPI/Completion.py
On lengthy SQL statements with lots of identifiers and aliases the performance was poor, this commit improves performance of smart completions for most widely used case - when prefix does not contain any dots (no parent object specified).
> Improved performance of smart completions

- SQLTools.sublime-settings
- SQLToolsAPI/Command.py
- SQLToolsAPI/Connection.py
- SQLToolsConnections.sublime-settings
Two new dict options under cli_options[type] are added in settings:
* env - always sets the vars to given value
* env_optional - sets the env vars only if sucessfully formatted
Default settings file is updated to support this new functionality.
Implementation for #106
> Added new PostgreSQL auth method using env vars

- SQLToolsConnections.sublime-settings
Forgot to rephrase the `pgpass.conf` related message in default Connections file.
This PR fixes that.
> Minor edit in default Connections file comments

- README.md
* added the feature highlight
* rearranged the feature list order
* rephrased the part with Fix Mac Path
> Update readme according to new functionality

- .bumpversion.cfg
- SQLTools.py
- messages.json
- messages/install.md
- messages/v0.9.2.md
Bumped version, updated changes files.
> Release v0.9.2

- .bumpversion.cfg
- SQLTools.py
- SQLTools.sublime-settings
- messages.json
- messages/v0.9.3.md
A simple change to pull identifiers (tables, columns) that are related to other schemas as well.
> Pull Oracle identifiers in all schemas

- SQLTools.sublime-settings
- SQLToolsAPI/Command.py
- SQLToolsAPI/Connection.py
First of all, just want to preface by saying that SQLTools is an amazing tool! I use it every day at work and it makes executing query snippets much easier and speeds up my workflow tremendously. I have some ideas that would improve my specific workflow that I believe would also improve the project as a whole. However, I want to spend some time getting acquainted with the codebase before I go forth with suggesting any of these ideas.
In the meantime, I am just getting my feet wet with the codebase and I figured I go ahead and work on this small but significant change to the show_query setting of the plugin.
In the current version, when enabling show_query, it will place the query information on top of the results if in regular output mode, and if in stream output mode, places it on the …
> Configure placement of show_query in non-stream output

- index.md
Update the documentation to reflect the new changes introduced by PR #116.
> Update documentation entry for show_query (Related to #116)

- SQLTools.sublime-settings
https://github.com/mtxr/SQLTools/issues/115
> Related to: #115

- .bumpversion.cfg
- SQLTools.py
- messages.json
- messages/v0.9.4.md
Version bump & added new feature descriptions for release.
> Release v0.9.4

- SQLTools.py
> Fix status bar message

- .bumpversion.cfg
- SQLTools.py
- messages.json
- messages/v0.9.5.md
> Release v0.9.5

- SQLTools.sublime-settings
> Fixes problems with MySQL quoted identifiers

- .bumpversion.cfg
- SQLTools.py
- messages.json
- messages/v0.9.6.md
> Release v0.9.6

- .bumpversion.cfg
- ISSUE_TEMPLATE.md
- SQLTools.py
- messages.json
- messages/v0.9.7.md
> Release v0.9.7

- SQLTools.sublime-settings
- SQLToolsConnections.sublime-settings
So far tested only on Windows.
Related to #120 #52
> Add MSSQL support by using native sqlcmd CLI

- SQLTools.py
- SQLTools.sublime-settings
> Add setting focus_on_result

- SQLTools.py
- SQLToolsAPI/Storage.py
https://github.com/mtxr/SQLTools/issues/144 Why create empty settings file on the User folder?
> Stop creating settings

- README.md
- SQLToolsConnections.sublime-settings
Minor fixes after merging Snowflake support
> Minor fixes after merging Snowflake support

- SQLTools.py
Enables a user to get to the desired table easier if table name is selected in the active view.
> Fill quick panel with tables with a selection from the active view.

- SQLToolsAPI/Connection.py
This should hopefully fix #190.
> Bump timeout to 60 seconds for internal commands

- ISSUE_TEMPLATE.md
- README.md
- messages/install.md
> Update website links
