mtxr/SublimeText-SQLTools

SQLToolsAPI/lib/sqlparse/keywords.py
Hey, I am working on a Postgres-based Data Warehousing project. The formatting tool has been a life-saver in the recent days. However, I had to add a couple of keywords to the sqlparse library. Check it out. 
Best,
Demetrio
=> sqlparse: Added keywords for PostgreSQL

SQLTools.py, SQLTools.sublime-settings, SQLToolsAPI/Command.py, SQLToolsAPI/Connection.py
Define a minimum limit to avoid accidental big and slow queries.
If query is a SELECT and doesn't contain a LIMIT and safe_limit is set, then add a LIMIT
option= safe_limit
&
Show above the results the executed query, including a timestamp and duration
option= show_query
=> Add options: safe_limit, show_query and expand_to_paragraph

SQLToolsAPI/Connection.py
I found that the code lines described in `before` items in the `SQLTools.sublime-settings` are not run when we execute the  package commands other than the `ST: Execute` package command.
I think they should be run, because there are some problems such as we get wrapped lines in the result of `ST: Show Table Records` command on Oracle DB (though the results of `ST: Execute` are not wrapped), unless we execute them.
This PR fixes the problem. I wonder if there are better ways to fix, but it works.
Sorry that I've tested on only Oracle DB, but I think it doesn't cause problems on other DBs.
Thanks,
=> Make `Connection.py` to run commands in `before` items in the main setting file.

SQLTools.py
This is for #63 .
Just add a line `Table "TABLE"` before the records. I tested on only Oracle DB, but this modification is not DB vendor specific.
Thanks!
=> Show table name on the result of `ST: Show Table Records` command

SQLTools.sublime-settings
Add additional SQL syntax highlights to selectors list
in default settings. This will make autocomplete to work with
these addtional syntax highlights out of the box:
* PostgreSQL Syntax Highlighting
https://github.com/tkopets/sublime-postgresql-syntax
* Postgres PL pgSQL
https://github.com/mulander/postgres.tmbundle
* Oracle PL SQL
https://github.com/mulander/oracle.tmbundle
* TSQLEasy
https://github.com/tosher/TSQLEasy
fixes #61
=> show autocomplete for popular SQL syntax highlights

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, Default.sublime-commands, SQLTools.py, SQLTools.sublime-settings, SQLToolsAPI/Connection.py
This commit is for #64 .
Added `ST: Explain Plan` command to get execution plan for the query.
This is still a draft because I worked only on Oracle.
This feature requires DB specific codes therefore testing with each DB is necessary, but currently I don't have environments with DB other than Oracle. I need to set up DBs to complete this PR but it should take some more time, so I'll be very glad if somebody help making it handling other DBs.
Thanks.
=> Added explain plan command

README.md
Simple readme update to mention new explain query plan functionality.
I will prepare the same update to `gh-pages` branch shortly.
=> mention new explain query command in README

SQLToolsAPI/Command.py, SQLToolsAPI/Connection.py
The configurable setting of "thread_timeout" is now taken into account when executing commands that can potentially take a long time to complete.
Configurable "thread_timeout" setting is used for these commands:
* Execute query
* Explain query
* Show table records
Also, fixes the code for terminating the process on Windows platforms.
Fixes #79 
@mtxr 
I'm don't commit these directly to master as I want you to review those changes (if you have a possibility to do so), as I'm not entirely sure this code is inline with your vision of how this should work.
=> Take into account configurable "thread_timeout" for long running commands

SQLTools.py, SQLTools.sublime-settings, SQLToolsAPI/Completion.py, SQLToolsAPI/ParseUtils.py, SQLToolsAPI/Utils.py, SQLToolsAPI/__init__.py
New "smarter" completions are shown, when possible.
The main difference from previous completions are proper completions for table columns: `table.column|`, as well as completions for table aliases:
`select a.| from tbl a`
and completions for join conditions:
`select * from tbl_a a inner join tbl_b b on |`
The current paragraph of SQL text is parsed by already existing `sqlparse` library.
A small demo can be seen in discussion https://github.com/mtxr/SQLTools/issues/67
=> Smart completions

.bumpversion.cfg, SQLTools.py, SQLToolsAPI/Command.py, messages.json, messages/v0.9.1.md
Improved process handling when streaming results.
Combine stdout and stderr for better output.
Fixes #90, #91, #92
Bumped version.
Release notes included - ready for next release.
=> improved process, stdout, stderr handling

SQLTools.py, SQLToolsAPI/Command.py
Honor `use_streams` setting when executing saved queries and queries from history.
Additionally, on MacOS the process is set to `None` after all of the output has been processed, so add the additional check for that in Command code.
=> Use stream output for saved queries and history

SQLTools.py, SQLTools.sublime-settings
Fixed "clear_output" for panel output.
Also, the default for setting "clear_output" is set to true, so it is consistent with previous behavior.
Fix for #102
=> Fixed "clear_output" for panel output

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, Default.sublime-commands, SQLTools.py
Added Execute All File command.
Minor key binding change:
`Execute All File` command got a key binding `ctrl+e ctrl+a`, which overlapped with `List Queries`.
Instead of rarely used `List Queries` (`ctrl+e ctrl+a`) which is now set by default to (`ctrl+e ctrl+l`) for better mnemonic (list).
Fixes #114
=> Add Execute All File command

SQLTools.py
Fixes #125.
Since we actually don't need the connection if the user just opens the contents of saved query the Connection list will not be shown.
=> Fix List and Open Saved Queries

Default (Windows).sublime-keymap, Default.sublime-commands, SQLTools.py
As described in issue #126, added the ability to insert saved queries directly into existing tab at the current selection(s). Try it out and let me know what you think. I'll update the website once the green light is given.
This new feature expands the `st_list_queries` command to take a new argument for mode: "insert" which will perform the insertion of a selected saved query.
The keybind for this feature is currently mapped to `Ctrl+E, Ctrl+I`.
=> Add List and Insert Saved Queries

SQLTools.py
SQLTools will display a shorter and more appropriate error message in the
status bar and in the console if SQLTools failed to parse Settings and
Connections JSON files.
=> Better messages if settings could not be parsed

SQLToolsAPI/Completion.py
This commit fixes a bug when SQLTools did not show any completions when uppercase alias was used.
Fixes #142
=> Display completions for upper cased aliases

SQLTools.py, SQLToolsAPI/Completion.py
Dolar sign is treated as part of an identifier when evaluating autocompletion prefix.
Dolar sign is escaped when formatting autocompletion items (otherwise Sublime Text assumes it a variable).
Fixes #152
=> Fix completions for identifiers with dollar sign

SQLTools.sublime-settings
When connecting to MySQL use the flag `--default-character-set=utf8`, which should hopefully solve most of the encoding issues in SQLTools.
=> Use utf8 encoding in MySQL output

SQLTools.py, SQLTools.sublime-settings, SQLToolsAPI/Command.py, SQLToolsAPI/Connection.py, SQLToolsConnections.sublime-settings
The highlight of this PR and the main structural and functional changes include: 
- changes how top level and per-query `options` apply to CLI invocations
- changes how `before` and `after` applied (top level and per-query)
- introduction of new `execute` named query section which is used when executing statements with `ST: Execute` and friends (Execute All File, Execute Query from History, etc)
- since above-mentioned items affect configuration for each RDBMS, review each of them, when possible fix, add new or missing functionality.
This one is a somewhat lengthy pull request, but as you can see it is for a good reason.
Here is a more detailed list of things that got fixed or improved in this PR:
- Ensure `before` and `after` runs on all commands.
Make sure that `before` and newly …
=> Add MSSQL support, unify and fix "before" & "after" sql config, review most RDBMS configs

SQLTools.py, SQLTools.sublime-settings, SQLToolsConnections.sublime-settings
Quick summary:
* Review settings, move important options to the top
* Add more comments explaining the options in settings
* Add `Vertica` and `Firebird` to list of sample connections
* Adds support for `Vertica` quoted identifiers
* Removes unnecessary try...catch when loading project-specific connections
=> Review settings, move important options to the top

SQLTools.py
Fixes per-project connection settings, as one would get the exception listed below if Sublime Text does not have an open project.
`AttributeError: 'NoneType' object has no attribute 'get'`
=> Fixes per-project connection settings

SQLTools.py, SQLTools.sublime-settings, SQLToolsAPI/Connection.py
**Add more options for expanding the empty selection.**
Instead of config option `expand_to_paragraph`, introduce new option called `expand_to`, which can be configured to expand empty selection to:
- `line` - current line(s)
- `paragraph` - current paragraph(s)
- `file` - current file (view)
Also, keep the compatibility with old setting `expand_to_paragraph`, if set to `true`, then `expand_to` is considered to be set to `paragraph`.
**Improve the way the output is shown - the output panel is not shown until the first output from DB CLI arrives.**
Do not display the output panel right away - wait for query results to arrive and then display it.
This improves how SQLTools behaves for long running queries, so the user does not have to stare at the empty panel, waiting for results to arrive. …
=> Add more options for expanding the empty selection, improve output

SQLTools.sublime-settings, SQLToolsConnections.sublime-settings
**Review and improve PostgreSQL, MySQL, MSSQL configs**
PostgreSQL
* `host`, `port`, `username` are now optional (can be set via environment vars and other means). See PostgreSQL docs.
MySQL
* add configurable MySQL connection charset via `--default-character-set`
* add `--no-auto-rehash` and `--compress` to improve MySQL startup time and improve latency on slow networks
* `host`, `port`, `username` are now optional (can be set via `--defaults-extra-file` and `--login-path`)
* supply password via env var `MYSQL_PWD` to avoid security warning
* other minor tweaks
MSSQL
* for internal commands send (and ignore) errors to stderr
**Remove unused settings option `unescape_quotes`**
Encoding-related issues #162 #164
=> Review and improve PostgreSQL, MySQL, MSSQL configs

.bumpversion.cfg, README.md, SQLTools.py, messages.json, messages/install.md, messages/v0.9.8.md
* Add MSSQL support via native `sqlcmd` CLI
* Add more options for expanding the empty selection. Instead of config option `expand_to_paragraph`, introduce new option called `expand_to`, which can be configured to expand empty selection to: `line`, `paragraph` or `file`
* General review/improvement of each DB config
* Use the `encoding` option supplied in connection settings when writing to standard input and reading from standard output of CLI command
* Changes how top level and per-query `options` apply to CLI invocations
* Changes how `before` and `after` applied (top level and per-query)
* Introduction of new `execute` named query section which is used when executing statements with `ST: Execute` and friends
* Now all named query formatting is done via `str.format()`, therefore all …
=> Release v0.9.8

SQLToolsAPI/Connection.py
Check if connection `encoding` is a valid python encoding, if not use `utf-8` encoding.
If connection `encoding` is set to `null` (which results in python `None`), then use `utf-8` encoding.
Fixes #177
=> Check if valid encoding, defaulting to utf-8

.bumpversion.cfg, SQLTools.py, messages.json, messages/v0.9.9.md
* Use `utf-8` encoding if Connection `encoding` is not a valid python encoding
* Exception when Connection `encoding` is set to null [#177]
=> Release v0.9.9

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, Default.sublime-commands, SQLTools.py
Adding new SQLTools command `st_format_all` which can be used to format the whole file.
Also fixes inconsistencies between Windows, Linux and Mac keybindings - Linux and Mac didn't have a keybinding for one of the commands.
Fixes #182
=> Add new command to Format All File

Default.sublime-commands, SQLTools.py
When you change the database structure, i would like to update the data without having to restart sublime or to reselect the connection
=> Add command to reset table, columns and functions cache

Default.sublime-commands, SQLTools.py, SQLToolsAPI/Completion.py
Reduces the time to show the list of connections.
Improves the performance of SQLTools completions significantly.
The completion object is initialized once when connection data is (re)loaded.
Also, incorporate the new command for reloading the connection data (cached list of connection identifiers). However, the name and wording of this command are slightly changed to be a bit more generic.
Thank you, @agvald!
=> Improve completions and connections listing performance

README.md, SQLTools.sublime-settings, SQLToolsConnections.sublime-settings
I've added support for [Snowflake's `snowsql` CLI](https://docs.snowflake.net/manuals/user-guide/snowsql-start.html). 
`execute`, `show records`, `desc`, `desc table`, and `columns` all implemented, but Snowflake doesn't yet have an `explain` equivalent for `snowsql` yet. 
Included an example configuration with instructions on configuring with either single sign-on or simple Snowflake auth.
=> Snowflake (snowsql) support

README.md, SQLTools.py, SQLTools.sublime-settings, SQLToolsAPI/Completion.py, SQLToolsAPI/Storage.py, SQLToolsConnections.sublime-settings
Add a setting to disable completion for certain selectors instead of hard-coding them.
This should fix (enable) completions for SQL code embedded as a string in other languages.
Fixes #199
=>  Add a setting to disable completion for selectors

SQLTools.sublime-settings
The old query was not compatible with the most recent PostgreSQL v11.
The new query, unlike the old one, will also additionally return the custom aggregate functions.
=> Fix compatibility issue with PostgreSQL v11 (func)

.bumpversion.cfg, SQLTools.py, messages.json, messages/v0.9.10.md, messages/v0.9.11.md, messages/v0.9.12.md
* Snowflake (`snowsql`) support
* Added support for prompting of the connection parameters
* Table/view/function selection quick panel is pre-populated with the text of the current selection
* New command `ST: Refresh Connection Data` (internal name `st_refresh_connection_data`) to reload the list of database objects
* Improve performance (completions and connection listing)
* Add a configurable setting to enable/disable completion for certain selectors (`autocomplete_selectors_ignore`, `autocomplete_selectors_active`)
* Fix PostgreSQL v11 compatibility issue (functions were not listed)
* Do not create an empty settings file [#144]
* Bump timeout to 60 seconds for internal commands
* Use python core logging for logs
=> Release v0.9.12
